"""empty message

Revision ID: 441479f6a154
Revises: b112aa0fc419
Create Date: 2026-01-29 23:19:59.720794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441479f6a154'
down_revision = 'b112aa0fc419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
